// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs$LidcoreBsNode = require("@lidcore/bs-node/src/fs.js");
var Stream$LidcoreBsNode = require("@lidcore/bs-node/src/stream.js");

function download(f, path) {
  var readable = f.createReadStream();
  var writeable = Fs$LidcoreBsNode.createWriteStream(/* Some */[path], /* None */0, /* None */0, /* () */0);
  Stream$LidcoreBsNode.pipe(readable, writeable);
  return Stream$LidcoreBsNode.on(writeable, /* `Finish */[
              991147123,
              (function () {
                  console.log("finished");
                  return /* () */0;
                })
            ]);
}

function exists(prim, prim$1) {
  prim.exists(prim$1);
  return /* () */0;
}

exports.exists = exists;
exports.download = download;
/* Fs-LidcoreBsNode Not a pure module */
