// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function exists(prim, prim$1) {
  prim.exists(prim$1);
  return /* () */0;
}

exports.exists = exists;
/* No side effect */
