// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Storage = require("@google-cloud/storage");

function make(config, _) {
  return Storage(config);
}

exports.make = make;
/* @google-cloud/storage Not a pure module */
