// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Callback = require("bs-callback/src/callback.js");
var File$BsGcloudStorage = require("./File.bs.js");
var Storage = require("@google-cloud/storage");

function make(config, _) {
  return Storage(config);
}

var s = Storage(/* None */0);

var b = s.bucket("m.lidco.io");

var f = b.file("4eef6f7783b8b708080c8f2f7d7087ed62eda9b1/9a07a146-6fcb-3531-bfd2-d46bbe4cecbd.wav");

function checkFile(param) {
  return Callback.$great$great((function (param) {
                return File$BsGcloudStorage.exists(f, param);
              }), (function (e) {
                console.log(e);
                return (function (param) {
                    return Callback.$$return(/* () */0, param);
                  });
              }), param);
}

Callback.finish(/* None */0, checkFile);

exports.make = make;
exports.s = s;
exports.b = b;
exports.f = f;
exports.checkFile = checkFile;
/* s Not a pure module */
